version: "3.1"
services:
  php:
    container_name: tic-tac-toe_dev
    build:
      context: ./config/docker/php/
      dockerfile: Dockerfile
    image: tic-tac-toe_php
    environment:
      TIMEZONE: Europe/Berlin
    volumes:
      - .:/var/www/html:cached
